version: '3.3'

services:
  mp3mdf:
    #image: ghcr.io/rui1610/mp3mdf:main
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_mp3mdf
    container_name: mp3mdf
    restart: "no"
    hostname: mp3mdf
    entrypoint: "/mp3mdf/mp3mdf"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - GENIUS_ACCESS_TOKEN=${GENIUS_ACCESS_TOKEN}
      - MP3MDF_INPUT_FOLDER=${MP3MDF_INPUT_FOLDER}
      - MP3MDF_OUTPUT_FOLDER=${MP3MDF_OUTPUT_FOLDER}
      - TZ="Europe/Berlin"
    volumes:
      - "${MP3MDF_INPUT_FOLDER}:/mp3mdf/data/input"
      - "${MP3MDF_OUTPUT_FOLDER}:/mp3mdf/data/output"

  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    restart: always
    hostname: youtubedl
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ="Europe/Berlin"
      - ALLOW_CONFIG_MUTATIONS=true
    volumes:
      - "${MP3MDF_INPUT_FOLDER}:/app/audio"
      - "${FOLDER_MULTIMEDIA}/youtube-dl/video:/app/video"
    ports: 
      - "${PORT_YOUTUBEDL}:17442"

networks:
  multimediaaudio: