#! /usr/bin/env python

from util.files import getAllMp3Files, moveFile
from constants.folders import FOLDER_INPUT
from pathlib import Path
from model.song import Song

temp = Path(__file__).resolve()


allMp3Files = getAllMp3Files(FOLDER_INPUT)

for thisMp3File in allMp3Files:
    song = Song(thisMp3File)
    moveFile(song.audio_file, thisMp3File)
